image: node:latest

stages:
  - npm
  - test

npm:
  stage: npm
  script:
    - npm install
    - cd backend
    - npm install --legacy-peer-deps
    - npm i ts-node -D --legacy-peer-deps
    - cd ..
    - cd frontend
    - npm install --legacy-peer-deps
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - npm
  script:
    - cd backend
    - npm test